= Vert.x Maven Starter

This project is a template to start your own Vert.x project using Apache Maven.

== Prerequisites

* Apache Maven
* JDK 8+

== Building the project

To perform a full build of the project, just use:

----
mvn clean install
----

It generates a project _jar_ in the `target` directory.

== Running the project

Once you can reliably build the project, you can check that everything works with:

[source]
----
mvn test exec:java
----

The command compiles the project and runs the tests, then  it launches the application, so you can check by yourself. Open your browser to http://localhost:8080.

== Packaging the project (for deployment)

To build the project, just use:

----
mvn clean package
----

It generates a _fat-jar_ in the `target` directory. The fat jar encapsulates all required dependencies and can be deployed/executed as a stand-alone process.

== Running the project from the fat Jar

Once you have packaged the project, you can check that everything works with:

[source]
----
java -jar target/vertx-start-project-1.0-SNAPSHOT-fat.jar
----

The command launches the application as a stand-alone Java process. Open your browser to http://localhost:8080.

